services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      TZ: 'Australia/Melbourne'
      ServerIP: '192.168.4.201'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    environment:
      OPENAI_API_KEY: ""    # Replace with your OpenAI API key
      GEMINI_API_KEY: ""      # Replace with your Gemini API key
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data

  portainer:
    image: cr.portainer.io/portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443"
      # - "8000:8000"  # Optional: Portainer Edge agent tunnel
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    volumes:
      - minecraftdata:/data
      - /home/Minecraft/plugins:/plugins
    ports:
      - "30000:30000"
    environment:
      EULA: "TRUE"
      TYPE: "BUKKIT"
      OPS: ""
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped

volumes:
  portainer_data:
  minecraftdata:
    external: true
